package com.enterprise.order.gateway.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Error envelope for responses generated by the gateway itself (route not found,
 * rate limit exceeded, circuit breaker open, internal gateway errors).
 * <p>
 * Deliberately mirrors the JSON contract of {@code com.enterprise.order.shared.dto.BaseResponse}
 * (success / message / data / error{code, message, details} / timestamp) so clients see one
 * consistent shape platform-wide. The gateway cannot depend on the servlet-based shared-library
 * (this service is reactive/Netty), hence this gateway-owned copy.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class GatewayErrorResponse {

    private boolean success;
    private String message;
    private Object data;
    private ErrorDetail error;
    private LocalDateTime timestamp;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ErrorDetail {
        private String code;
        private String message;
        private String details;
    }

    public static GatewayErrorResponse of(String code, String message, String details) {
        return GatewayErrorResponse.builder()
                .success(false)
                .error(new ErrorDetail(code, message, details))
                .timestamp(LocalDateTime.now())
                .build();
    }
}
